### PR TITLE
Update pandas version

### PR DESCRIPTION
**Pull request by fealho**
CU-86b03c9bp.

### CODE REVIEW

**Comment by sdv-team** [comment]
Task linked: [CU-86b03c9bp DeepEcho - Update pandas version](https://app.clickup.com/t/86b03c9bp)

**Review by rwedge — APPROVED** [review]

**Review by amontanez24 — COMMENTED** [review]
Can we update the flake8-pytest-style version here too?

**Comment by fealho** [comment]
> Can we update the flake8-pytest-style version here too?

@amontanez24 DeepEcho doesn't use flake8.

**Review by gsheni — APPROVED** [review]

**Review by amontanez24 — APPROVED** [review]

**Comment by amontanez24** [comment]
> > Can we update the flake8-pytest-style version here too?
> 
> @amontanez24 DeepEcho doesn't use flake8.

oh that's right we switched to ruff for this one

**Pull request merged**
